### PR TITLE
Handle parentheses in ingredients

### LINKED ISSUE #11: Ingredient parsing issue: "6 (1/4 inch thick) slices" parsed as "4 inch thick slices" on allrecipes
**Describe the bug**
I found a recipe that had failed to parse the ingredient quantity correctly.

**To Reproduce**
1. Look at [this recipe page on RecipeRadar](https://www.reciperadar.com/#search&action=view&id=RA6FKVR9Tadeoy8KxiwnFz6bJVme1ZC1dsac). See that it requires "4 inch thick) slices Italian **bread**..."
3. Click through to the [original recipe](https://www.allrecipes.com/recipe/111236/tubbys-pesto-panini/): It actually requires "6 (1/4 inch thick) slices Italian bread"

**Expected behavior**
It should magically know that "6" is the quantity and "1/4 inch thick" is an adjectival phrase / part of the ingredient description. I don't know what the best way to do this is. Perhaps the `(` (character which isn't a quantity or unit) is a good hint that that's where the quantity ends and the description starts? (I assume `(` is ignored?)

Now should I make this with 4x inch-thick slices, or one 4-inch-thick slice...?

### PR DESCRIPTION
**Pull request by Thra11**
### Describe the reason for these changes and the problem that they solve
Attempt to fix an ingredient which was parsed incorrectly because the ingredient description contained parentheses (#11).

### Briefly summarize the changes
1. Add a couple of test cases for ingredient descriptions which contain parentheses.
2. Adjust the parser grammar so that the new test cases pass, without introducing any other failures.

### How have the changes been tested?
1. By running the test suite

**List any issues that this change relates to**
Fixes #11.

### CODE REVIEW

**Comment by jayaddison** [comment]
@Thra11 After testing out various approaches locally, I think I prefer the route you were taking with https://github.com/Thra11/ingreedy-py/commit/57ce9fe1a38f2f965af5cc2d2428979f77e35879 over this one.

The one suggestion I'd have there might be to use the rule name `amount_with_property` rather than `amount_with_other`.  We may actually want to keep and return these properties as part of the ingredient metadata in future.  What do you reckon?

**Comment by Thra11** [comment]
> We may actually want to keep and return these properties as part of the ingredient metadata in future. What do you reckon?

As you can probably guess, I wasn't sure which approach was best. My thinking behind choosing the approach I did was something like this...
The original recipe has this text:
> 6 (1/4 inch thick) slices Italian bread with sesame seeds (also known as Scali) 

The page on reciperadar will recombine the parsed quantity, unit, and ingredient (with the ingredient keyword in bold). If we ignore/discard the bit in parentheses, we'll see this:
> 6 slices Italian **bread** with sesame seeds (also known as Scali)

If we keep it as part of the ingredient, we'll see this:
> 6 (1/4 inch thick) slices Italian **bread** with sesame seeds (also known as Scali)

In this particular case, either would be fine. They both capture the fact that you need 6 slices of bread (as opposed to e.g. 6 loaves of bread). However, my thinking was that we can't necessarily predict what the recipe author will put in parentheses, so it's better to err on the side of caution and keep any text which we don't understand as text, just in case it's significant.

Essentially:
* If the parser doesn't know what "(1/4 inch thick)" represents, it doesn't know if it's significant or not.
* Ordering is inconsistent. Sometimes you get "½ (12 ounce) jar ...", which I believe the parser 'understands' as equivalent to 6oz, but you're equally likely to see "½ jar (12 ounce) ...", in which case the "(12 ounce)" gets matched by the catchall parser as part of the ingredient. Instead of "6 (1/4 inch thick) slices Italian bread", the recipe could equally have said, "6 slices (1/4 inch thick) Italian bread" or "6 slices Italian bread (1/4 inch thick)". Why should we discard the "(1/4 inch thick)" from the first case, but keep it for the other two?

Ultimately, it's your project, and you probably have a better idea what sort of things typically appear in the parentheses and whether they are important, so it's up to you!

**Comment by jayaddison** [comment]
Thanks @Thra11 - I agree it's challenging to figure out any definitive rules that will work in most/all cases.

The approach I'd like to take is to gradually add more and more test cases to try to show how the system 'should' work, and to try (as far as possible) to implement those via a grammar, so that it's always deterministic, compehrensible (hopefully.. if it stays simple enough) and fixable.

I'll have a bit more of a think about this and might end up adding some more test cases before merging one or other of the PRs.

**Comment by jayaddison** [comment]
Thanks @Thra11 for reporting and working on this - I've opted to merge #13 for now, which also builds on some of your commits.

**Pull request closed without merging**
